# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/lms.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/lms.proto\x12\x03lms\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"3\n\x10RegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"?\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"@\n\nGetRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x15\n\roptional_data\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"x\n\x0bGetResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x1b\n\x13pending_assignments\x18\x02 \x03(\t\x12\x1d\n\x15submitted_assignments\x18\x03 \x03(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\"8\n\x0bPostRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x1e\n\x0cPostResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0eLogoutResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xff\x01\n\x03LMS\x12>\n\x0fRegisterStudent\x12\x14.lms.RegisterRequest\x1a\x15.lms.RegisterResponse\x12.\n\x05Login\x12\x11.lms.LoginRequest\x1a\x12.lms.LoginResponse\x12(\n\x03Get\x12\x0f.lms.GetRequest\x1a\x10.lms.GetResponse\x12+\n\x04Post\x12\x10.lms.PostRequest\x1a\x11.lms.PostResponse\x12\x31\n\x06Logout\x12\x12.lms.LogoutRequest\x1a\x13.lms.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.lms_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REGISTERREQUEST']._serialized_start=24
  _globals['_REGISTERREQUEST']._serialized_end=77
  _globals['_REGISTERRESPONSE']._serialized_start=79
  _globals['_REGISTERRESPONSE']._serialized_end=130
  _globals['_LOGINREQUEST']._serialized_start=132
  _globals['_LOGINREQUEST']._serialized_end=182
  _globals['_LOGINRESPONSE']._serialized_start=184
  _globals['_LOGINRESPONSE']._serialized_end=247
  _globals['_GETREQUEST']._serialized_start=249
  _globals['_GETREQUEST']._serialized_end=313
  _globals['_GETRESPONSE']._serialized_start=315
  _globals['_GETRESPONSE']._serialized_end=435
  _globals['_POSTREQUEST']._serialized_start=437
  _globals['_POSTREQUEST']._serialized_end=493
  _globals['_POSTRESPONSE']._serialized_start=495
  _globals['_POSTRESPONSE']._serialized_end=525
  _globals['_LOGOUTREQUEST']._serialized_start=527
  _globals['_LOGOUTREQUEST']._serialized_end=557
  _globals['_LOGOUTRESPONSE']._serialized_start=559
  _globals['_LOGOUTRESPONSE']._serialized_end=591
  _globals['_LMS']._serialized_start=594
  _globals['_LMS']._serialized_end=849
# @@protoc_insertion_point(module_scope)
